create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username varchar(50) unique not null,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.caffeine_logs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  drink_name varchar(50) not null,
  caffeine_mg integer not null default 0,
  sugar_g integer default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  title varchar(255) not null,
  task_date date not null default current_date,
  is_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.todos add column if not exists task_date date;
update public.todos
set task_date = (created_at at time zone 'Asia/Hong_Kong')::date
where task_date is null;
alter table public.todos alter column task_date set default current_date;
alter table public.todos alter column task_date set not null;

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists todos_set_updated_at on public.todos;
create trigger todos_set_updated_at
before update on public.todos
for each row
execute function public.set_updated_at();

alter table public.users enable row level security;
alter table public.caffeine_logs enable row level security;
alter table public.todos enable row level security;

drop policy if exists "prototype users read" on public.users;
drop policy if exists "prototype users insert" on public.users;
drop policy if exists "prototype caffeine read" on public.caffeine_logs;
drop policy if exists "prototype caffeine insert" on public.caffeine_logs;
drop policy if exists "prototype todos read" on public.todos;
drop policy if exists "prototype todos insert" on public.todos;
drop policy if exists "prototype todos update" on public.todos;

create policy "prototype users read"
on public.users for select
to anon
using (true);

create policy "prototype users insert"
on public.users for insert
to anon
with check (true);

create policy "prototype caffeine read"
on public.caffeine_logs for select
to anon
using (true);

create policy "prototype caffeine insert"
on public.caffeine_logs for insert
to anon
with check (true);

create policy "prototype todos read"
on public.todos for select
to anon
using (true);

create policy "prototype todos insert"
on public.todos for insert
to anon
with check (true);

create policy "prototype todos update"
on public.todos for update
to anon
using (true)
with check (true);

insert into public.users (username, password_hash)
values ('early-eight-demo', 'prototype-only-no-login')
on conflict (username) do nothing;

insert into public.caffeine_logs (user_id, drink_name, caffeine_mg, sugar_g, created_at)
select u.id, v.drink_name, v.caffeine_mg, v.sugar_g, now() - v.offset_value
from public.users u
cross join (
  values
    ('冰美式', 140, 0, interval '7 hours'),
    ('燕麦拿铁', 95, 8, interval '4 hours'),
    ('冷萃', 180, 0, interval '1 hour')
) as v(drink_name, caffeine_mg, sugar_g, offset_value)
where u.username = 'early-eight-demo'
  and not exists (
    select 1
    from public.caffeine_logs existing
    where existing.user_id = u.id
  );

insert into public.todos (user_id, title, task_date, is_completed)
select u.id, v.title, current_date, v.is_completed
from public.users u
cross join (
  values
    ('改 defense PPT 第 7 页', true),
    ('整理早会纪要', false),
    ('把接口文档补上示例', false),
    ('提交周报，不写文学作品', true)
) as v(title, is_completed)
where u.username = 'early-eight-demo'
  and not exists (
    select 1
    from public.todos existing
    where existing.user_id = u.id
  );
